package com.youversion.platform.reader.theme.ui

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import com.youversion.platform.reader.theme.tokens.BibleColorDarkTokens
import com.youversion.platform.reader.theme.tokens.BibleColorLightTokens

@Immutable
class BibleReaderColorScheme(
    val canvasPrimary: Color,
    val canvasSecondary: Color,
    val surfacePrimary: Color,
    val surfaceSecondary: Color,
    val surfaceTertiary: Color,
    val surfaceEverDark: Color,
    val surfaceEverLight: Color,
    val textPrimary: Color,
    val textMuted: Color,
    val textInverted: Color,
    val textEverDark: Color,
    val textEverLight: Color,
    val buttonPrimary: Color,
    val buttonSecondary: Color,
    val buttonContrast: Color,
    val borderPrimary: Color,
    val borderSecondary: Color,
    val borderMuted: Color,
    val borderContrast: Color,
    val utilityActiveSelected: Color,
    val utilitySuccess: Color,
    val utilityInfo: Color,
    val utilityAlert: Color,
    val utilityCaution: Color,
    val brandAccent: Color,
    val brandWarmNeutral: Color,
    val brandLogoText: Color,
)

fun lightBibleReaderColorScheme(
    canvasPrimary: Color = BibleColorLightTokens.CanvasPrimary,
    canvasSecondary: Color = BibleColorLightTokens.CanvasSecondary,
    surfacePrimary: Color = BibleColorLightTokens.SurfacePrimary,
    surfaceSecondary: Color = BibleColorLightTokens.SurfaceSecondary,
    surfaceTertiary: Color = BibleColorLightTokens.SurfaceTertiary,
    surfaceEverDark: Color = BibleColorLightTokens.SurfaceEverDark,
    surfaceEverLight: Color = BibleColorLightTokens.SurfaceEverLight,
    textPrimary: Color = BibleColorLightTokens.TextPrimary,
    textMuted: Color = BibleColorLightTokens.TextMuted,
    textInverted: Color = BibleColorLightTokens.TextInverted,
    textEverDark: Color = BibleColorLightTokens.TextEverDark,
    textEverLight: Color = BibleColorLightTokens.TextEverLight,
    buttonPrimary: Color = BibleColorLightTokens.ButtonPrimary,
    buttonSecondary: Color = BibleColorLightTokens.ButtonSecondary,
    buttonContrast: Color = BibleColorLightTokens.ButtonContrast,
    borderPrimary: Color = BibleColorLightTokens.BorderPrimary,
    borderSecondary: Color = BibleColorLightTokens.BorderSecondary,
    borderMuted: Color = BibleColorLightTokens.BorderMuted,
    borderContrast: Color = BibleColorLightTokens.BorderContrast,
    utilityActiveSelected: Color = BibleColorLightTokens.UtilityActiveSelected,
    utilitySuccess: Color = BibleColorLightTokens.UtilitySuccess,
    utilityInfo: Color = BibleColorLightTokens.UtilityInfo,
    utilityAlert: Color = BibleColorLightTokens.UtilityAlert,
    utilityCaution: Color = BibleColorLightTokens.UtilityCaution,
    brandAccent: Color = BibleColorLightTokens.BrandAccent,
    brandWarmNeutral: Color = BibleColorLightTokens.BrandWarmNeutral,
    brandLogoText: Color = BibleColorLightTokens.BrandLogoText,
): BibleReaderColorScheme =
    BibleReaderColorScheme(
        canvasPrimary = canvasPrimary,
        canvasSecondary = canvasSecondary,
        surfacePrimary = surfacePrimary,
        surfaceSecondary = surfaceSecondary,
        surfaceTertiary = surfaceTertiary,
        surfaceEverDark = surfaceEverDark,
        surfaceEverLight = surfaceEverLight,
        textPrimary = textPrimary,
        textMuted = textMuted,
        textInverted = textInverted,
        textEverDark = textEverDark,
        textEverLight = textEverLight,
        buttonPrimary = buttonPrimary,
        buttonSecondary = buttonSecondary,
        buttonContrast = buttonContrast,
        borderPrimary = borderPrimary,
        borderSecondary = borderSecondary,
        borderMuted = borderMuted,
        borderContrast = borderContrast,
        utilityActiveSelected = utilityActiveSelected,
        utilitySuccess = utilitySuccess,
        utilityInfo = utilityInfo,
        utilityAlert = utilityAlert,
        utilityCaution = utilityCaution,
        brandAccent = brandAccent,
        brandWarmNeutral = brandWarmNeutral,
        brandLogoText = brandLogoText,
    )

fun darkBibleReaderColorScheme(
    canvasPrimary: Color = BibleColorDarkTokens.CanvasPrimary,
    canvasSecondary: Color = BibleColorDarkTokens.CanvasSecondary,
    surfacePrimary: Color = BibleColorDarkTokens.SurfacePrimary,
    surfaceSecondary: Color = BibleColorDarkTokens.SurfaceSecondary,
    surfaceTertiary: Color = BibleColorDarkTokens.SurfaceTertiary,
    surfaceEverDark: Color = BibleColorDarkTokens.SurfaceEverDark,
    surfaceEverLight: Color = BibleColorDarkTokens.SurfaceEverLight,
    textPrimary: Color = BibleColorDarkTokens.TextPrimary,
    textMuted: Color = BibleColorDarkTokens.TextMuted,
    textInverted: Color = BibleColorDarkTokens.TextInverted,
    textEverDark: Color = BibleColorDarkTokens.TextEverDark,
    textEverLight: Color = BibleColorDarkTokens.TextEverLight,
    buttonPrimary: Color = BibleColorDarkTokens.ButtonPrimary,
    buttonSecondary: Color = BibleColorDarkTokens.ButtonSecondary,
    buttonContrast: Color = BibleColorDarkTokens.ButtonContrast,
    borderPrimary: Color = BibleColorDarkTokens.BorderPrimary,
    borderSecondary: Color = BibleColorDarkTokens.BorderSecondary,
    borderMuted: Color = BibleColorDarkTokens.BorderMuted,
    borderContrast: Color = BibleColorDarkTokens.BorderContrast,
    utilityActiveSelected: Color = BibleColorDarkTokens.UtilityActiveSelected,
    utilitySuccess: Color = BibleColorDarkTokens.UtilitySuccess,
    utilityInfo: Color = BibleColorDarkTokens.UtilityInfo,
    utilityAlert: Color = BibleColorDarkTokens.UtilityAlert,
    utilityCaution: Color = BibleColorDarkTokens.UtilityCaution,
    brandAccent: Color = BibleColorDarkTokens.BrandAccent,
    brandWarmNeutral: Color = BibleColorDarkTokens.BrandWarmNeutral,
    brandLogoText: Color = BibleColorDarkTokens.BrandLogoText,
): BibleReaderColorScheme =
    BibleReaderColorScheme(
        canvasPrimary = canvasPrimary,
        canvasSecondary = canvasSecondary,
        surfacePrimary = surfacePrimary,
        surfaceSecondary = surfaceSecondary,
        surfaceTertiary = surfaceTertiary,
        surfaceEverDark = surfaceEverDark,
        surfaceEverLight = surfaceEverLight,
        textPrimary = textPrimary,
        textMuted = textMuted,
        textInverted = textInverted,
        textEverDark = textEverDark,
        textEverLight = textEverLight,
        buttonPrimary = buttonPrimary,
        buttonSecondary = buttonSecondary,
        buttonContrast = buttonContrast,
        borderPrimary = borderPrimary,
        borderSecondary = borderSecondary,
        borderMuted = borderMuted,
        borderContrast = borderContrast,
        utilityActiveSelected = utilityActiveSelected,
        utilitySuccess = utilitySuccess,
        utilityInfo = utilityInfo,
        utilityAlert = utilityAlert,
        utilityCaution = utilityCaution,
        brandAccent = brandAccent,
        brandWarmNeutral = brandWarmNeutral,
        brandLogoText = brandLogoText,
    )

internal val LocalBibleReaderColorScheme = staticCompositionLocalOf { lightBibleReaderColorScheme() }
