package com.youversion.platform.ui.views.components

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * Material Symbols `cancel` (filled) — the circled cross the Swift SDK clears its search fields
 * with. Generated by Valkyrie; regenerate rather than hand-editing the path.
 */
internal val ClearSearch: ImageVector by lazy(LazyThreadSafetyMode.NONE) {
    ImageVector
        .Builder(
            name = "ClearSearch",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                moveToRelative(336f, 680f)
                lineToRelative(144f, -144f)
                lineToRelative(144f, 144f)
                lineToRelative(56f, -56f)
                lineToRelative(-144f, -144f)
                lineToRelative(144f, -144f)
                lineToRelative(-56f, -56f)
                lineToRelative(-144f, 144f)
                lineToRelative(-144f, -144f)
                lineToRelative(-56f, 56f)
                lineToRelative(144f, 144f)
                lineToRelative(-144f, 144f)
                lineToRelative(56f, 56f)
                close()
                moveTo(480f, 880f)
                quadToRelative(-83f, 0f, -156f, -31.5f)
                reflectiveQuadTo(197f, 763f)
                quadToRelative(-54f, -54f, -85.5f, -127f)
                reflectiveQuadTo(80f, 480f)
                quadToRelative(0f, -83f, 31.5f, -156f)
                reflectiveQuadTo(197f, 197f)
                quadToRelative(54f, -54f, 127f, -85.5f)
                reflectiveQuadTo(480f, 80f)
                quadToRelative(83f, 0f, 156f, 31.5f)
                reflectiveQuadTo(763f, 197f)
                quadToRelative(54f, 54f, 85.5f, 127f)
                reflectiveQuadTo(880f, 480f)
                quadToRelative(0f, 83f, -31.5f, 156f)
                reflectiveQuadTo(763f, 763f)
                quadToRelative(-54f, 54f, -127f, 85.5f)
                reflectiveQuadTo(480f, 880f)
                close()
            }
        }.build()
}
